#ifndef BITFIELDS_H_
#define BITFIELDS_H_

/* RCU */               
#define RCU                                 ((RCU_TypeDef *) RCU_BASE)
/* APB2 */
#define RCU_APB2EN_TIMER10EN                ((uint32_t)(1UL << 21))
#define RCU_APB2EN_TIMER9EN                 ((uint32_t)(1UL << 20))
#define RCU_APB2EN_TIMER8EN                 ((uint32_t)(1UL << 19))
#define RCU_APB2EN_USART0EN                 ((uint32_t)(1UL << 14))
#define RCU_APB2EN_TIMER7EN                 ((uint32_t)(1UL << 13))
#define RCU_APB2EN_SPI0EN                   ((uint32_t)(1UL << 12))
#define RCU_APB2EN_TIMER0EN                 ((uint32_t)(1UL << 11))
#define RCU_APB2EN_ADC1EN                   ((uint32_t)(1UL << 10))
#define RCU_APB2EN_ADC0EN                   ((uint32_t)(1UL << 9))
#define RCU_APB2EN_PGEN                     ((uint32_t)(1UL << 8))
#define RCU_APB2EN_PFEN                     ((uint32_t)(1UL << 7))
#define RCU_APB2EN_PEEN                     ((uint32_t)(1UL << 6))
#define RCU_APB2EN_PDEN                     ((uint32_t)(1UL << 5))
#define RCU_APB2EN_PCEN                     ((uint32_t)(1UL << 4))
#define RCU_APB2EN_PBEN                     ((uint32_t)(1UL << 3))
#define RCU_APB2EN_PAEN                     ((uint32_t)(1UL << 2))
#define RCU_APB2EN_AFEN                     ((uint32_t)(1UL << 0))
/* APB1 */
#define RCU_APB1EN_DACEN                    ((uint32_t)(1UL << 29))
#define RCU_APB1EN_I2C1EN                   ((uint32_t)(1UL << 22))
#define RCU_APB1EN_I2C0EN                   ((uint32_t)(1UL << 21))
#define RCU_APB1EN_USART1EN                 ((uint32_t)(1UL << 17))
#define RCU_APB1EN_SPI2EN                   ((uint32_t)(1UL << 15))
#define RCU_APB1EN_SPI1EN                   ((uint32_t)(1UL << 14))
#define RCU_APB1EN_TIMER13EN                ((uint32_t)(1UL << 8))
#define RCU_APB1EN_TIMER12EN                ((uint32_t)(1UL << 7))
#define RCU_APB1EN_TIMER11EN                ((uint32_t)(1UL << 6))
#define RCU_APB1EN_TIMER6EN                 ((uint32_t)(1UL << 5))
#define RCU_APB1EN_TIMER5EN                 ((uint32_t)(1UL << 4))
#define RCU_APB1EN_TIMER4EN                 ((uint32_t)(1UL << 3))
#define RCU_APB1EN_TIMER3EN                 ((uint32_t)(1UL << 2))
#define RCU_APB1EN_TIMER2EN                 ((uint32_t)(1UL << 1))
#define RCU_APB1EN_TIMER1EN                 ((uint32_t)(1UL << 0))
/* GPIO */              
#define GPIOA                               ((GPIO_TypeDef *) GPIO_BASE)
#define GPIOB                               ((GPIO_TypeDef *) (GPIO_BASE + 0x400))
#define GPIOC                               ((GPIO_TypeDef *) (GPIO_BASE + 0x800))
#define GPIOD                               ((GPIO_TypeDef *) (GPIO_BASE + 0xC00))
#define GPIOE                               ((GPIO_TypeDef *) (GPIO_BASE + 0x1000))
#define GPIOF                               ((GPIO_TypeDef *) (GPIO_BASE + 0x1400))
#define GPIOG                               ((GPIO_TypeDef *) (GPIO_BASE + 0x1800))
/* CTL0 */              
#define GPIO_CTL0_CTL7_1                    ((uint32_t)(1UL << 31))
#define GPIO_CTL0_CTL7_0                    ((uint32_t)(1UL << 30))
#define GPIO_CTL0_MD7_1                     ((uint32_t)(1UL << 29))
#define GPIO_CTL0_MD7_0                     ((uint32_t)(1UL << 28))
#define GPIO_CTL0_CTL6_1                    ((uint32_t)(1UL << 27))
#define GPIO_CTL0_CTL6_0                    ((uint32_t)(1UL << 26))
#define GPIO_CTL0_MD6_1                     ((uint32_t)(1UL << 25))
#define GPIO_CTL0_MD6_0                     ((uint32_t)(1UL << 24))
#define GPIO_CTL0_CTL5_1                    ((uint32_t)(1UL << 23))
#define GPIO_CTL0_CTL5_0                    ((uint32_t)(1UL << 22))
#define GPIO_CTL0_MD5_1                     ((uint32_t)(1UL << 21))
#define GPIO_CTL0_MD5_0                     ((uint32_t)(1UL << 20))
#define GPIO_CTL0_CTL4_1                    ((uint32_t)(1UL << 19))
#define GPIO_CTL0_CTL4_0                    ((uint32_t)(1UL << 18))
#define GPIO_CTL0_MD4_1                     ((uint32_t)(1UL << 17))
#define GPIO_CTL0_MD4_0                     ((uint32_t)(1UL << 16))
#define GPIO_CTL0_CTL3_1                    ((uint32_t)(1UL << 15))
#define GPIO_CTL0_CTL3_0                    ((uint32_t)(1UL << 14))
#define GPIO_CTL0_MD3_1                     ((uint32_t)(1UL << 13))
#define GPIO_CTL0_MD3_0                     ((uint32_t)(1UL << 12))
#define GPIO_CTL0_CTL2_1                    ((uint32_t)(1UL << 11))
#define GPIO_CTL0_CTL2_0                    ((uint32_t)(1UL << 10))
#define GPIO_CTL0_MD2_1                     ((uint32_t)(1UL << 9))
#define GPIO_CTL0_MD2_0                     ((uint32_t)(1UL << 8))
#define GPIO_CTL0_CTL1_1                    ((uint32_t)(1UL << 7))
#define GPIO_CTL0_CTL1_0                    ((uint32_t)(1UL << 6))
#define GPIO_CTL0_MD1_1                     ((uint32_t)(1UL << 5))
#define GPIO_CTL0_MD1_0                     ((uint32_t)(1UL << 4))
#define GPIO_CTL0_CTL0_1                    ((uint32_t)(1UL << 3))
#define GPIO_CTL0_CTL0_0                    ((uint32_t)(1UL << 2))
#define GPIO_CTL0_MD0_1                     ((uint32_t)(1UL << 1))
#define GPIO_CTL0_MD0_0                     ((uint32_t)(1UL << 0))
/* CTL1 */              
#define GPIO_CTL1_CTL15_1                   ((uint32_t)(1UL << 31))
#define GPIO_CTL1_CTL15_0                   ((uint32_t)(1UL << 30))
#define GPIO_CTL1_MD15_1                    ((uint32_t)(1UL << 29))
#define GPIO_CTL1_MD15_0                    ((uint32_t)(1UL << 28))
#define GPIO_CTL1_CTL14_1                   ((uint32_t)(1UL << 27))
#define GPIO_CTL1_CTL14_0                   ((uint32_t)(1UL << 26))
#define GPIO_CTL1_MD14_1                    ((uint32_t)(1UL << 25))
#define GPIO_CTL1_MD14_0                    ((uint32_t)(1UL << 24))
#define GPIO_CTL1_CTL13_1                   ((uint32_t)(1UL << 23))
#define GPIO_CTL1_CTL13_0                   ((uint32_t)(1UL << 22))
#define GPIO_CTL1_MD13_1                    ((uint32_t)(1UL << 21))
#define GPIO_CTL1_MD13_0                    ((uint32_t)(1UL << 20))
#define GPIO_CTL1_CTL12_1                   ((uint32_t)(1UL << 19))
#define GPIO_CTL1_CTL12_0                   ((uint32_t)(1UL << 18))
#define GPIO_CTL1_MD12_1                    ((uint32_t)(1UL << 17))
#define GPIO_CTL1_MD12_0                    ((uint32_t)(1UL << 16))
#define GPIO_CTL1_CTL11_1                   ((uint32_t)(1UL << 15))
#define GPIO_CTL1_CTL11_0                   ((uint32_t)(1UL << 14))
#define GPIO_CTL1_MD11_1                    ((uint32_t)(1UL << 13))
#define GPIO_CTL1_MD11_0                    ((uint32_t)(1UL << 12))
#define GPIO_CTL1_CTL10_1                   ((uint32_t)(1UL << 11))
#define GPIO_CTL1_CTL10_0                   ((uint32_t)(1UL << 10))
#define GPIO_CTL1_MD10_1                    ((uint32_t)(1UL << 9))
#define GPIO_CTL1_MD10_0                    ((uint32_t)(1UL << 8))
#define GPIO_CTL1_CTL9_1                    ((uint32_t)(1UL << 7))
#define GPIO_CTL1_CTL9_0                    ((uint32_t)(1UL << 6))
#define GPIO_CTL1_MD9_1                     ((uint32_t)(1UL << 5))
#define GPIO_CTL1_MD9_0                     ((uint32_t)(1UL << 4))
#define GPIO_CTL1_CTL8_1                    ((uint32_t)(1UL << 3))
#define GPIO_CTL1_CTL8_0                    ((uint32_t)(1UL << 2))
#define GPIO_CTL1_MD8_1                     ((uint32_t)(1UL << 1))
#define GPIO_CTL1_MD8_0                     ((uint32_t)(1UL << 0))
/* ISTAT */             
#define GPIO_ISTAT_ISTAT15                  ((uint32_t)(1UL << 15))  
#define GPIO_ISTAT_ISTAT14                  ((uint32_t)(1UL << 14))  
#define GPIO_ISTAT_ISTAT13                  ((uint32_t)(1UL << 13))  
#define GPIO_ISTAT_ISTAT12                  ((uint32_t)(1UL << 12))  
#define GPIO_ISTAT_ISTAT11                  ((uint32_t)(1UL << 11))  
#define GPIO_ISTAT_ISTAT10                  ((uint32_t)(1UL << 10))  
#define GPIO_ISTAT_ISTAT9                   ((uint32_t)(1UL << 9))  
#define GPIO_ISTAT_ISTAT8                   ((uint32_t)(1UL << 8))  
#define GPIO_ISTAT_ISTAT7                   ((uint32_t)(1UL << 7))  
#define GPIO_ISTAT_ISTAT6                   ((uint32_t)(1UL << 6))  
#define GPIO_ISTAT_ISTAT5                   ((uint32_t)(1UL << 5))  
#define GPIO_ISTAT_ISTAT4                   ((uint32_t)(1UL << 4))  
#define GPIO_ISTAT_ISTAT3                   ((uint32_t)(1UL << 3))  
#define GPIO_ISTAT_ISTAT2                   ((uint32_t)(1UL << 2))  
#define GPIO_ISTAT_ISTAT1                   ((uint32_t)(1UL << 1))  
#define GPIO_ISTAT_ISTAT0                   ((uint32_t)(1UL << 0))  
/* OCTL */              
#define GPIO_OCTL_OCTL15                    ((uint32_t)(1UL << 15))
#define GPIO_OCTL_OCTL14                    ((uint32_t)(1UL << 14))
#define GPIO_OCTL_OCTL13                    ((uint32_t)(1UL << 13))
#define GPIO_OCTL_OCTL12                    ((uint32_t)(1UL << 12))
#define GPIO_OCTL_OCTL11                    ((uint32_t)(1UL << 11))
#define GPIO_OCTL_OCTL10                    ((uint32_t)(1UL << 10))
#define GPIO_OCTL_OCTL9                     ((uint32_t)(1UL << 9))
#define GPIO_OCTL_OCTL8                     ((uint32_t)(1UL << 8))
#define GPIO_OCTL_OCTL7                     ((uint32_t)(1UL << 7))
#define GPIO_OCTL_OCTL6                     ((uint32_t)(1UL << 6))
#define GPIO_OCTL_OCTL5                     ((uint32_t)(1UL << 5))
#define GPIO_OCTL_OCTL4                     ((uint32_t)(1UL << 4))
#define GPIO_OCTL_OCTL3                     ((uint32_t)(1UL << 3))
#define GPIO_OCTL_OCTL2                     ((uint32_t)(1UL << 2))
#define GPIO_OCTL_OCTL1                     ((uint32_t)(1UL << 1))
#define GPIO_OCTL_OCTL0                     ((uint32_t)(1UL << 0))
/* SPD */
#define GPIO_SPD_SPD15                      ((uint32_t)(1UL << 15))
#define GPIO_SPD_SPD14                      ((uint32_t)(1UL << 14))
#define GPIO_SPD_SPD13                      ((uint32_t)(1UL << 13))
#define GPIO_SPD_SPD12                      ((uint32_t)(1UL << 12))
#define GPIO_SPD_SPD11                      ((uint32_t)(1UL << 11))
#define GPIO_SPD_SPD10                      ((uint32_t)(1UL << 10))
#define GPIO_SPD_SPD9                       ((uint32_t)(1UL << 9))
#define GPIO_SPD_SPD8                       ((uint32_t)(1UL << 8))
#define GPIO_SPD_SPD7                       ((uint32_t)(1UL << 7))
#define GPIO_SPD_SPD6                       ((uint32_t)(1UL << 6))
#define GPIO_SPD_SPD5                       ((uint32_t)(1UL << 5))
#define GPIO_SPD_SPD4                       ((uint32_t)(1UL << 4))
#define GPIO_SPD_SPD3                       ((uint32_t)(1UL << 3))
#define GPIO_SPD_SPD2                       ((uint32_t)(1UL << 2))
#define GPIO_SPD_SPD1                       ((uint32_t)(1UL << 1))
#define GPIO_SPD_SPD0                       ((uint32_t)(1UL << 0))

/* AFIO */

/* EXTI */
#define EXTI                                ((EXTI_TypeDef *) (EXTI_BASE))
/* INTEN */
#define EXTI_INTEN_INTEN15                  ((uint32_t)(1UL << 15))
#define EXTI_INTEN_INTEN14                  ((uint32_t)(1UL << 14))
#define EXTI_INTEN_INTEN13                  ((uint32_t)(1UL << 13))
#define EXTI_INTEN_INTEN12                  ((uint32_t)(1UL << 12))
#define EXTI_INTEN_INTEN11                  ((uint32_t)(1UL << 11))
#define EXTI_INTEN_INTEN10                  ((uint32_t)(1UL << 10))
#define EXTI_INTEN_INTEN9                   ((uint32_t)(1UL << 9))
#define EXTI_INTEN_INTEN8                   ((uint32_t)(1UL << 8))
#define EXTI_INTEN_INTEN7                   ((uint32_t)(1UL << 7))
#define EXTI_INTEN_INTEN6                   ((uint32_t)(1UL << 6))
#define EXTI_INTEN_INTEN5                   ((uint32_t)(1UL << 5))
#define EXTI_INTEN_INTEN4                   ((uint32_t)(1UL << 4))
#define EXTI_INTEN_INTEN3                   ((uint32_t)(1UL << 3))
#define EXTI_INTEN_INTEN2                   ((uint32_t)(1UL << 2))
#define EXTI_INTEN_INTEN1                   ((uint32_t)(1UL << 1))
#define EXTI_INTEN_INTEN0                   ((uint32_t)(1UL << 0))
/* EVEN */
#define EXTI_EVEN_EVEN15                    ((uint32_t)(1UL << 15))
#define EXTI_EVEN_EVEN14                    ((uint32_t)(1UL << 14))
#define EXTI_EVEN_EVEN13                    ((uint32_t)(1UL << 13))
#define EXTI_EVEN_EVEN12                    ((uint32_t)(1UL << 12))
#define EXTI_EVEN_EVEN11                    ((uint32_t)(1UL << 11))
#define EXTI_EVEN_EVEN10                    ((uint32_t)(1UL << 10))
#define EXTI_EVEN_EVEN9                     ((uint32_t)(1UL << 9))
#define EXTI_EVEN_EVEN8                     ((uint32_t)(1UL << 8))
#define EXTI_EVEN_EVEN7                     ((uint32_t)(1UL << 7))
#define EXTI_EVEN_EVEN6                     ((uint32_t)(1UL << 6))
#define EXTI_EVEN_EVEN5                     ((uint32_t)(1UL << 5))
#define EXTI_EVEN_EVEN4                     ((uint32_t)(1UL << 4))
#define EXTI_EVEN_EVEN3                     ((uint32_t)(1UL << 3))
#define EXTI_EVEN_EVEN2                     ((uint32_t)(1UL << 2))
#define EXTI_EVEN_EVEN1                     ((uint32_t)(1UL << 1))
#define EXTI_EVEN_EVEN0                     ((uint32_t)(1UL << 0))
/* RTEN */
#define EXTI_RTEN_RTEN15                    ((uint32_t)(1UL << 15))
#define EXTI_RTEN_RTEN14                    ((uint32_t)(1UL << 14))
#define EXTI_RTEN_RTEN13                    ((uint32_t)(1UL << 13))
#define EXTI_RTEN_RTEN12                    ((uint32_t)(1UL << 12))
#define EXTI_RTEN_RTEN11                    ((uint32_t)(1UL << 11))
#define EXTI_RTEN_RTEN10                    ((uint32_t)(1UL << 10))
#define EXTI_RTEN_RTEN9                     ((uint32_t)(1UL << 9))
#define EXTI_RTEN_RTEN8                     ((uint32_t)(1UL << 8))
#define EXTI_RTEN_RTEN7                     ((uint32_t)(1UL << 7))
#define EXTI_RTEN_RTEN6                     ((uint32_t)(1UL << 6))
#define EXTI_RTEN_RTEN5                     ((uint32_t)(1UL << 5))
#define EXTI_RTEN_RTEN4                     ((uint32_t)(1UL << 4))
#define EXTI_RTEN_RTEN3                     ((uint32_t)(1UL << 3))
#define EXTI_RTEN_RTEN2                     ((uint32_t)(1UL << 2))
#define EXTI_RTEN_RTEN1                     ((uint32_t)(1UL << 1))
#define EXTI_RTEN_RTEN0                     ((uint32_t)(1UL << 0))
/* FTEN */
#define EXTI_FTEN_FTEN15                    ((uint32_t)(1UL << 15))
#define EXTI_FTEN_FTEN14                    ((uint32_t)(1UL << 14))
#define EXTI_FTEN_FTEN13                    ((uint32_t)(1UL << 13))
#define EXTI_FTEN_FTEN12                    ((uint32_t)(1UL << 12))
#define EXTI_FTEN_FTEN11                    ((uint32_t)(1UL << 11))
#define EXTI_FTEN_FTEN10                    ((uint32_t)(1UL << 10))
#define EXTI_FTEN_FTEN9                     ((uint32_t)(1UL << 9))
#define EXTI_FTEN_FTEN8                     ((uint32_t)(1UL << 8))
#define EXTI_FTEN_FTEN7                     ((uint32_t)(1UL << 7))
#define EXTI_FTEN_FTEN6                     ((uint32_t)(1UL << 6))
#define EXTI_FTEN_FTEN5                     ((uint32_t)(1UL << 5))
#define EXTI_FTEN_FTEN4                     ((uint32_t)(1UL << 4))
#define EXTI_FTEN_FTEN3                     ((uint32_t)(1UL << 3))
#define EXTI_FTEN_FTEN2                     ((uint32_t)(1UL << 2))
#define EXTI_FTEN_FTEN1                     ((uint32_t)(1UL << 1))
#define EXTI_FTEN_FTEN0                     ((uint32_t)(1UL << 0))
/* SWIEV */
#define EXTI_SWIEV_SWIEV15                  ((uint32_t)(1UL << 15))
#define EXTI_SWIEV_SWIEV14                  ((uint32_t)(1UL << 14))
#define EXTI_SWIEV_SWIEV13                  ((uint32_t)(1UL << 13))
#define EXTI_SWIEV_SWIEV12                  ((uint32_t)(1UL << 12))
#define EXTI_SWIEV_SWIEV11                  ((uint32_t)(1UL << 11))
#define EXTI_SWIEV_SWIEV10                  ((uint32_t)(1UL << 10))
#define EXTI_SWIEV_SWIEV9                   ((uint32_t)(1UL << 9))
#define EXTI_SWIEV_SWIEV8                   ((uint32_t)(1UL << 8))
#define EXTI_SWIEV_SWIEV7                   ((uint32_t)(1UL << 7))
#define EXTI_SWIEV_SWIEV6                   ((uint32_t)(1UL << 6))
#define EXTI_SWIEV_SWIEV5                   ((uint32_t)(1UL << 5))
#define EXTI_SWIEV_SWIEV4                   ((uint32_t)(1UL << 4))
#define EXTI_SWIEV_SWIEV3                   ((uint32_t)(1UL << 3))
#define EXTI_SWIEV_SWIEV2                   ((uint32_t)(1UL << 2))
#define EXTI_SWIEV_SWIEV1                   ((uint32_t)(1UL << 1))
#define EXTI_SWIEV_SWIEV0                   ((uint32_t)(1UL << 0))
/* PD */
#define EXTI_PD_PD15                        ((uint32_t)(1UL << 15))
#define EXTI_PD_PD14                        ((uint32_t)(1UL << 14))
#define EXTI_PD_PD13                        ((uint32_t)(1UL << 13))
#define EXTI_PD_PD12                        ((uint32_t)(1UL << 12))
#define EXTI_PD_PD11                        ((uint32_t)(1UL << 11))
#define EXTI_PD_PD10                        ((uint32_t)(1UL << 10))
#define EXTI_PD_PD9                         ((uint32_t)(1UL << 9))
#define EXTI_PD_PD8                         ((uint32_t)(1UL << 8))
#define EXTI_PD_PD7                         ((uint32_t)(1UL << 7))
#define EXTI_PD_PD6                         ((uint32_t)(1UL << 6))
#define EXTI_PD_PD5                         ((uint32_t)(1UL << 5))
#define EXTI_PD_PD4                         ((uint32_t)(1UL << 4))
#define EXTI_PD_PD3                         ((uint32_t)(1UL << 3))
#define EXTI_PD_PD2                         ((uint32_t)(1UL << 2))
#define EXTI_PD_PD1                         ((uint32_t)(1UL << 1))
#define EXTI_PD_PD0                         ((uint32_t)(1UL << 0))    
/* TIMER_ADVANCED */                
#define TIMER0                              ((TIMER_A_TypeDef *) (TIMER_BASE + 0x12C00))
#define TIMER7                              ((TIMER_A_TypeDef *) (TIMER_BASE + 0x13400))
/* TIMER_L0 */              
#define TIMER1                              ((TIMER_L0_TypeDef *) TIMER_BASE)
#define TIMER2                              ((TIMER_L0_TypeDef *) (TIMER_BASE + 0x400))
#define TIMER3                              ((TIMER_L0_TypeDef *) (TIMER_BASE + 0x800))
#define TIMER4                              ((TIMER_L0_TypeDef *) (TIMER_BASE + 0xC00))
/* CTL0 */              
#define TIMER_L0_CTL0_CKDIV1                ((uint32_t)(1UL << 9))
#define TIMER_L0_CTL0_CKDIV0                ((uint32_t)(1UL << 8))
#define TIMER_L0_CTL0_ARSE                  ((uint32_t)(1UL << 7))
#define TIMER_L0_CTL0_CAM1                  ((uint32_t)(1UL << 6))
#define TIMER_L0_CTL0_CAM0                  ((uint32_t)(1UL << 5))
#define TIMER_L0_CTL0_DIR                   ((uint32_t)(1UL << 4))
#define TIMER_L0_CTL0_SPM                   ((uint32_t)(1UL << 3))
#define TIMER_L0_CTL0_UPS                   ((uint32_t)(1UL << 2))
#define TIMER_L0_CTL0_UPDIS                 ((uint32_t)(1UL << 1))
#define TIMER_L0_CTL0_CEN                   ((uint32_t)(1UL << 0))
/* DMAINTEN */              
#define TIMER_L0_DMAINTEN_UPIE              ((uint32_t)(1UL << 0))
/* INTF */
#define TIMER_L0_INTF_UPIF                  ((uint32_t)(1UL << 0))
/* CHCTL0 */
#define TIMER_L0_CHCTL0_CH1COMCTL_2         ((uint32_t)(1UL << 14))
#define TIMER_L0_CHCTL0_CH1COMCTL_1         ((uint32_t)(1UL << 13))
#define TIMER_L0_CHCTL0_CH1COMCTL_0         ((uint32_t)(1UL << 12))
/* CHCTL2 */
#define TIMER_L0_CHCTL2_CH3P                ((uint32_t)(1UL << 13))
#define TIMER_L0_CHCTL2_CH3EN               ((uint32_t)(1UL << 12))
#define TIMER_L0_CHCTL2_CH2P                ((uint32_t)(1UL << 9))
#define TIMER_L0_CHCTL2_CH2EN               ((uint32_t)(1UL << 8))
#define TIMER_L0_CHCTL2_CH1P                ((uint32_t)(1UL << 5))
#define TIMER_L0_CHCTL2_CH1EN               ((uint32_t)(1UL << 4))
#define TIMER_L0_CHCTL2_CH0P                ((uint32_t)(1UL << 1))
#define TIMER_L0_CHCTL2_CH0EN               ((uint32_t)(1UL << 0))
/* TIMER_L1 */              
#define TIMER8                              ((TIMER_L1_TypeDef *) (TIMER_BASE + 0x14C00))
#define TIMER11                             ((TIMER_L1_TypeDef *) (TIMER_BASE + 0x1800))
/* TIMER_L2 */              
#define TIMER9                              ((TIMER_L2_TypeDef *) (TIMER_BASE + 0x15000))
#define TIMER10                             ((TIMER_L2_TypeDef *) (TIMER_BASE + 0x15400))
#define TIMER12                             ((TIMER_L2_TypeDef *) (TIMER_BASE + 0x1C00))
#define TIMER13                             ((TIMER_L2_TypeDef *) (TIMER_BASE + 0x2000))
/* TIMER_BASIC */               
#define TIMER5                              ((TIMER_B_TypeDef *) (TIMER_BASE + 0x1000))
#define TIMER6                              ((TIMER_B_TypeDef *) (TIMER_BASE + 0x1400))
/* ADC */
#define ADC0                                ((ADC_TypeDef *) (ADC_BASE))
#define ADC1                                ((ADC_TypeDef *) (ADC_BASE + 0x400))
#define ADC2                                ((ADC_TypeDef *) (ADC_BASE + 0x1800))
/* STAT */
#define ADC_STAT_STRC                       ((uint32_t)(1UL << 4))      
#define ADC_STAT_EOC                        ((uint32_t)(1UL << 1))      
#define ADC_STAT_WDE                        ((uint32_t)(1UL << 0))   
/* CTL0 */   
#define ADC_CTL0_RWDEN                      ((uint32_t)(1UL << 23))
#define ADC_CTL0_SYNCM3                     ((uint32_t)(1UL << 19))
#define ADC_CTL0_SYNCM2                     ((uint32_t)(1UL << 18))
#define ADC_CTL0_SYNCM1                     ((uint32_t)(1UL << 17))
#define ADC_CTL0_SYNCM0                     ((uint32_t)(1UL << 16))      
#define ADC_CTL0_DISNUM2                    ((uint32_t)(1UL << 15))
#define ADC_CTL0_DISNUM1                    ((uint32_t)(1UL << 14))
#define ADC_CTL0_DISNUM0                    ((uint32_t)(1UL << 13))
#define ADC_CTL0_DISRC                      ((uint32_t)(1UL << 11))
#define ADC_CTL0_WDSC                       ((uint32_t)(1UL << 9))
#define ADC_CTL0_SM                         ((uint32_t)(1UL << 8))
#define ADC_CTL0_WDEE                       ((uint32_t)(1UL << 6))
#define ADC_CTL0_EOCIE                      ((uint32_t)(1UL << 5))
#define ADC_CTL0_WDCHSEL4                   ((uint32_t)(1UL << 4))
#define ADC_CTL0_WDCHSEL3                   ((uint32_t)(1UL << 3))
#define ADC_CTL0_WDCHSEL2                   ((uint32_t)(1UL << 2))
#define ADC_CTL0_WDCHSEL1                   ((uint32_t)(1UL << 1))
#define ADC_CTL0_WDCHSEL0                   ((uint32_t)(1UL << 0))
/* CTL1 */
#define ADC_CTL1_TSVREN                     ((uint32_t)(1UL << 23))      
#define ADC_CTL1_SWRCST                     ((uint32_t)(1UL << 22))      
#define ADC_CTL1_ETERC                      ((uint32_t)(1UL << 20))      
#define ADC_CTL1_ETSRC2                     ((uint32_t)(1UL << 19))      
#define ADC_CTL1_ETSRC1                     ((uint32_t)(1UL << 18))
#define ADC_CTL1_ETSRC0                     ((uint32_t)(1UL << 17))            
#define ADC_CTL1_DAL                        ((uint32_t)(1UL << 11))            
#define ADC_CTL1_DMA                        ((uint32_t)(1UL << 8))            
#define ADC_CTL1_RSTCLB                     ((uint32_t)(1UL << 3))            
#define ADC_CTL1_CLB                        ((uint32_t)(1UL << 2))            
#define ADC_CTL1_CTN                        ((uint32_t)(1UL << 1))      
#define ADC_CTL1_ADCON                      ((uint32_t)(1UL << 0))      
/* SAMPT1 */
#define ADC_SAMPT1_SPT1_2                   ((uint32_t)(1UL << 5))      
#define ADC_SAMPT1_SPT1_1                   ((uint32_t)(1UL << 4))
#define ADC_SAMPT1_SPT1_0                   ((uint32_t)(1UL << 3))
#define ADC_SAMPT1_SPT0_2                   ((uint32_t)(1UL << 2))      
#define ADC_SAMPT1_SPT0_1                   ((uint32_t)(1UL << 1))
#define ADC_SAMPT1_SPT0_0                   ((uint32_t)(1UL << 0))
/* RSQ0 */
#define ADC_RSQ0_RL3                        ((uint32_t)(1UL << 23))
#define ADC_RSQ0_RL2                        ((uint32_t)(1UL << 22))
#define ADC_RSQ0_RL1                        ((uint32_t)(1UL << 21))
#define ADC_RSQ0_RL0                        ((uint32_t)(1UL << 20))      
/* RSQ2 */
#define ADC_RSQ2_RSQ0                       ((uint32_t)(1UL << 0))      
/* DAC */
#define DAC                                 ((DAC_TypeDef *) (DAC_BASE))
/* CTL0 */
#define DAC_CTL0_DDMAEN1                    ((uint32_t)(1UL << 28))      
#define DAC_CTL0_DWBW1_3                    ((uint32_t)(1UL << 27))      
#define DAC_CTL0_DWBW1_2                    ((uint32_t)(1UL << 26))      
#define DAC_CTL0_DWBW1_1                    ((uint32_t)(1UL << 25))      
#define DAC_CTL0_DWBW1_0                    ((uint32_t)(1UL << 24))      
#define DAC_CTL0_DWM1_1                     ((uint32_t)(1UL << 23))      
#define DAC_CTL0_DWM1_0                     ((uint32_t)(1UL << 22))
#define DAC_CTL0_DTSEL1_2                   ((uint32_t)(1UL << 21))
#define DAC_CTL0_DTSEL1_1                   ((uint32_t)(1UL << 20))
#define DAC_CTL0_DTSEL1_0                   ((uint32_t)(1UL << 19))
#define DAC_CTL0_DTEN1                      ((uint32_t)(1UL << 18))
#define DAC_CTL0_DBOFF1                     ((uint32_t)(1UL << 17))
#define DAC_CTL0_DEN1                       ((uint32_t)(1UL << 16))
#define DAC_CTL0_DDMAEN0                    ((uint32_t)(1UL << 12)) 
#define DAC_CTL0_DWBW0_3                    ((uint32_t)(1UL << 11)) 
#define DAC_CTL0_DWBW0_2                    ((uint32_t)(1UL << 10)) 
#define DAC_CTL0_DWBW0_1                    ((uint32_t)(1UL << 9)) 
#define DAC_CTL0_DWBW0_0                    ((uint32_t)(1UL << 8)) 
#define DAC_CTL0_DWM0_1                     ((uint32_t)(1UL << 7)) 
#define DAC_CTL0_DWM0_0                     ((uint32_t)(1UL << 6))
#define DAC_CTL0_DTSEL0_2                   ((uint32_t)(1UL << 5))
#define DAC_CTL0_DTSEL0_1                   ((uint32_t)(1UL << 4))
#define DAC_CTL0_DTSEL0_0                   ((uint32_t)(1UL << 3))
#define DAC_CTL0_DTEN0                      ((uint32_t)(1UL << 2))
#define DAC_CTL0_DBOFF0                     ((uint32_t)(1UL << 1))
#define DAC_CTL0_DEN0                       ((uint32_t)(1UL << 0))
/* SWT */
#define DAC_CTL0_SWTR1                      ((uint32_t)(1UL << 1))
#define DAC_CTL0_SWTR0                      ((uint32_t)(1UL << 0))
/* OUT0_R12DH */
#define DAC_CTL0_OUT0_R12DH_OUT0_DH_0       ((uint32_t)(1UL << 0))
/* OUT0_L12DH */
#define DAC_CTL0_OUT0_L12DH_OUT0_DH_0       ((uint32_t)(1UL << 4))
/* OUT0_R8DH */
#define DAC_CTL0_OUT0_R8DH_OUT0_DH_0        ((uint32_t)(1UL << 0))
/* OUT1_R12DH */
#define DAC_CTL0_OUT1_R12DH_OUT1_DH_0       ((uint32_t)(1UL << 0))
/* OUT1_L12DH */
#define DAC_CTL0_OUT1_L12DH_OUT1_DH_0       ((uint32_t)(1UL << 4))
/* OUT1_R8DH */
#define DAC_CTL0_OUT1_R8DH_OUT1_DH_0        ((uint32_t)(1UL << 0))
/* R12DH */
#define DAC_CTL0_R12DH_OUT1_DH_0            ((uint32_t)(1UL << 16))
#define DAC_CTL0_R12DH_OUT0_DH_0            ((uint32_t)(1UL << 0))
/* L12DH */
#define DAC_CTL0_L12DH_OUT1_DH_0            ((uint32_t)(1UL << 20))
#define DAC_CTL0_L12DH_OUT0_DH_0            ((uint32_t)(1UL << 4))
/* R8DH */
#define DAC_CTL0_R8DH_OUT1_DH_0             ((uint32_t)(1UL << 8))
#define DAC_CTL0_R8DH_OUT0_DH_0             ((uint32_t)(1UL << 0))

/* USART */
#define USART0                              ((USART_TypeDef *) USART0_BASE)
#define USART1                              ((USART_TypeDef *) USART1_BASE)
/* STAT0 */
#define USART_STAT0_CTSF                    ((uint32_t)(1UL << 9))      
#define USART_STAT0_LBDF                    ((uint32_t)(1UL << 8))
#define USART_STAT0_TBE                     ((uint32_t)(1UL << 7))
#define USART_STAT0_TC                      ((uint32_t)(1UL << 6))
#define USART_STAT0_RBNE                    ((uint32_t)(1UL << 5))
#define USART_STAT0_IDLEF                   ((uint32_t)(1UL << 4))
#define USART_STAT0_ORERR                   ((uint32_t)(1UL << 3))
#define USART_STAT0_NERR                    ((uint32_t)(1UL << 2))
#define USART_STAT0_FERR                    ((uint32_t)(1UL << 1))
#define USART_STAT0_PERR                    ((uint32_t)(1UL << 0))
/* CTL0 */
#define USART_CTL0_UEN                      ((uint32_t)(1UL << 13))
#define USART_CTL0_WL                       ((uint32_t)(1UL << 12))
#define USART_CTL0_WM                       ((uint32_t)(1UL << 11))
#define USART_CTL0_PCEN                     ((uint32_t)(1UL << 10))
#define USART_CTL0_PM                       ((uint32_t)(1UL << 9))
#define USART_CTL0_PERRIE                   ((uint32_t)(1UL << 8))
#define USART_CTL0_TBEIE                    ((uint32_t)(1UL << 7))
#define USART_CTL0_TCIE                     ((uint32_t)(1UL << 6))
#define USART_CTL0_RBNEIE                   ((uint32_t)(1UL << 5))
#define USART_CTL0_IDLEIE                   ((uint32_t)(1UL << 4))
#define USART_CTL0_TEN                      ((uint32_t)(1UL << 3))
#define USART_CTL0_REN                      ((uint32_t)(1UL << 2))
#define USART_CTL0_RWU                      ((uint32_t)(1UL << 1))
#define USART_CTL0_SBKCMD                   ((uint32_t)(1UL << 0))
/* CTL1 */
#define USART_CTL1_LMEN                     ((uint32_t)(1UL << 14))
#define USART_CTL1_STB1                     ((uint32_t)(1UL << 13))
#define USART_CTL1_STB0                     ((uint32_t)(1UL << 12))
#define USART_CTL1_CKEN                     ((uint32_t)(1UL << 11))
#define USART_CTL1_CPL                      ((uint32_t)(1UL << 10))
#define USART_CTL1_CPH                      ((uint32_t)(1UL << 9))
#define USART_CTL1_CLEN                     ((uint32_t)(1UL << 8))
#define USART_CTL1_LBDIE                    ((uint32_t)(1UL << 6))
#define USART_CTL1_LBDLEN                   ((uint32_t)(1UL << 5))
#define USART_CTL1_ADDR3                    ((uint32_t)(1UL << 3))
#define USART_CTL1_ADDR2                    ((uint32_t)(1UL << 2))
#define USART_CTL1_ADDR1                    ((uint32_t)(1UL << 1))
#define USART_CTL1_ADDR0                    ((uint32_t)(1UL << 0))
/* CTL2 */
#define USART_CTL2_CTSIE                    ((uint32_t)(1UL << 10))
#define USART_CTL2_CTSEN                    ((uint32_t)(1UL << 9))
#define USART_CTL2_RTSEN                    ((uint32_t)(1UL << 8))
#define USART_CTL2_DENT                     ((uint32_t)(1UL << 7))
#define USART_CTL2_DENR                     ((uint32_t)(1UL << 6))
#define USART_CTL2_SCEN                     ((uint32_t)(1UL << 5))
#define USART_CTL2_NKEN                     ((uint32_t)(1UL << 4))
#define USART_CTL2_HDEN                     ((uint32_t)(1UL << 3))
#define USART_CTL2_IRLP                     ((uint32_t)(1UL << 2))
#define USART_CTL2_IREN                     ((uint32_t)(1UL << 1))
#define USART_CTL2_ERRIE                    ((uint32_t)(1UL << 0))
/* GP */
#define USART_GP_GUAT                       ((uint32_t)(1UL << 8))
#define USART_GP_PSC                        ((uint32_t)(1UL << 0))
/* I2C */
#define I2C0                                ((I2C_TypeDef *) I2C_BASE)
#define I2C1                                ((I2C_TypeDef *) (I2C_BASE + 400))
/* CTL0 */
#define I2C_CTL0_SRESET                     ((uint32_t)(1UL << 15))
#define I2C_CTL0_SALT                       ((uint32_t)(1UL << 13))
#define I2C_CTL0_PECTRANS                   ((uint32_t)(1UL << 12))
#define I2C_CTL0_POAP                       ((uint32_t)(1UL << 11))
#define I2C_CTL0_ACKEN                      ((uint32_t)(1UL << 10))
#define I2C_CTL0_STOP                       ((uint32_t)(1UL << 9))
#define I2C_CTL0_START                      ((uint32_t)(1UL << 8))
#define I2C_CTL0_DISSTRC                    ((uint32_t)(1UL << 7))
#define I2C_CTL0_GCEN                       ((uint32_t)(1UL << 6))
#define I2C_CTL0_PECEN                      ((uint32_t)(1UL << 5))
#define I2C_CTL0_ARPEN                      ((uint32_t)(1UL << 4))
#define I2C_CTL0_SMBSEL                     ((uint32_t)(1UL << 3))
#define I2C_CTL0_SMBEN                      ((uint32_t)(1UL << 1))
#define I2C_CTL0_I2CEN                      ((uint32_t)(1UL << 0))
/* CTL1 */
#define I2C_CTL1_DMALST                     ((uint32_t)(1UL << 12))
#define I2C_CTL1_DMAON                      ((uint32_t)(1UL << 11))
#define I2C_CTL1_BUFIE                      ((uint32_t)(1UL << 10))
#define I2C_CTL1_EVIE                       ((uint32_t)(1UL << 9))
#define I2C_CTL1_ERRIE                      ((uint32_t)(1UL << 8))
#define I2C_CTL1_I2CCLK                     ((uint32_t)(1UL << 0))
/* SADDR0 */
#define I2C_SADDR0_ADDFORMAT                ((uint32_t)(1UL << 15))
#define I2C_SADDR0_ADDRESS9                 ((uint32_t)(1UL << 9))
#define I2C_SADDR0_ADDRESS8                 ((uint32_t)(1UL << 8))
#define I2C_SADDR0_ADDRESS7                 ((uint32_t)(1UL << 7))
#define I2C_SADDR0_ADDRESS6                 ((uint32_t)(1UL << 6))
#define I2C_SADDR0_ADDRESS5                 ((uint32_t)(1UL << 5))
#define I2C_SADDR0_ADDRESS4                 ((uint32_t)(1UL << 4))
#define I2C_SADDR0_ADDRESS3                 ((uint32_t)(1UL << 3))
#define I2C_SADDR0_ADDRESS2                 ((uint32_t)(1UL << 2))
#define I2C_SADDR0_ADDRESS1                 ((uint32_t)(1UL << 1))
#define I2C_SADDR0_ADDRESS0                 ((uint32_t)(1UL << 0))
/* SADDR1 */
#define I2C_SADDR1_ADDRESS2_7               ((uint32_t)(1UL << 7))
#define I2C_SADDR1_ADDRESS2_6               ((uint32_t)(1UL << 6))
#define I2C_SADDR1_ADDRESS2_5               ((uint32_t)(1UL << 5))
#define I2C_SADDR1_ADDRESS2_4               ((uint32_t)(1UL << 4))
#define I2C_SADDR1_ADDRESS2_3               ((uint32_t)(1UL << 3))
#define I2C_SADDR1_ADDRESS2_2               ((uint32_t)(1UL << 2))
#define I2C_SADDR1_ADDRESS2_1               ((uint32_t)(1UL << 1))
#define I2C_SADDR1_DUADEN                   ((uint32_t)(1UL << 0))
/* STAT0 */
#define I2C_STAT0_SMBALT                    ((uint32_t)(1UL << 15))
#define I2C_STAT0_SMBTO                     ((uint32_t)(1UL << 14))
#define I2C_STAT0_PECERR                    ((uint32_t)(1UL << 12))
#define I2C_STAT0_OUERR                     ((uint32_t)(1UL << 11))
#define I2C_STAT0_AERR                      ((uint32_t)(1UL << 10))
#define I2C_STAT0_LOSTARB                   ((uint32_t)(1UL << 9))
#define I2C_STAT0_BERR                      ((uint32_t)(1UL << 8))
#define I2C_STAT0_TBE                       ((uint32_t)(1UL << 7))
#define I2C_STAT0_RBNE                      ((uint32_t)(1UL << 6))
#define I2C_STAT0_STPDET                    ((uint32_t)(1UL << 4))
#define I2C_STAT0_ADD10SEND                 ((uint32_t)(1UL << 3))
#define I2C_STAT0_BTC                       ((uint32_t)(1UL << 2))
#define I2C_STAT0_ADDSEND                   ((uint32_t)(1UL << 1))
#define I2C_STAT0_SBSEND                    ((uint32_t)(1UL << 0))
/* STAT1 */
#define I2C_STAT1_PECV7                     ((uint32_t)(1UL << 15))
#define I2C_STAT1_PECV6                     ((uint32_t)(1UL << 14))
#define I2C_STAT1_PECV5                     ((uint32_t)(1UL << 13))
#define I2C_STAT1_PECV4                     ((uint32_t)(1UL << 12))
#define I2C_STAT1_PECV3                     ((uint32_t)(1UL << 11))
#define I2C_STAT1_PECV2                     ((uint32_t)(1UL << 10))
#define I2C_STAT1_PECV1                     ((uint32_t)(1UL << 9))
#define I2C_STAT1_PECV0                     ((uint32_t)(1UL << 8))
#define I2C_STAT1_DUMODF                    ((uint32_t)(1UL << 7))
#define I2C_STAT1_HSTSMB                    ((uint32_t)(1UL << 6))
#define I2C_STAT1_DEFSMB                    ((uint32_t)(1UL << 5))
#define I2C_STAT1_RXGC                      ((uint32_t)(1UL << 4))
#define I2C_STAT1_TR                        ((uint32_t)(1UL << 2))
#define I2C_STAT1_I2CBSY                    ((uint32_t)(1UL << 1))
#define I2C_STAT1_MASTER                    ((uint32_t)(1UL << 0))
/* CKCFG */
#define I2C_CKCFG_FAST                      ((uint32_t)(1UL << 15))
#define I2C_CKCFG_DTCY                      ((uint32_t)(1UL << 14))
#define I2C_CKCFG_CLKC11                    ((uint32_t)(1UL << 11))
#define I2C_CKCFG_CLKC10                    ((uint32_t)(1UL << 10))
#define I2C_CKCFG_CLKC9                     ((uint32_t)(1UL << 9))
#define I2C_CKCFG_CLKC8                     ((uint32_t)(1UL << 8))
#define I2C_CKCFG_CLKC7                     ((uint32_t)(1UL << 7))
#define I2C_CKCFG_CLKC6                     ((uint32_t)(1UL << 6))
#define I2C_CKCFG_CLKC5                     ((uint32_t)(1UL << 5))
#define I2C_CKCFG_CLKC4                     ((uint32_t)(1UL << 4))
#define I2C_CKCFG_CLKC3                     ((uint32_t)(1UL << 3))
#define I2C_CKCFG_CLKC2                     ((uint32_t)(1UL << 2))
#define I2C_CKCFG_CLKC1                     ((uint32_t)(1UL << 1))
#define I2C_CKCFG_CLKC0                     ((uint32_t)(1UL << 0))

/* SPI */
#define SPI0                                ((SPI_TypeDef *) SPI0_BASE)
#define SPI1                                ((SPI_TypeDef *) SPI1_BASE)
#define SPI2                                ((SPI_TypeDef *) (SPI1_BASE + 400))
/* CTL0 */
#define SPI_CTL0_BDEN                       ((uint32_t)(1UL << 15))
#define SPI_CTL0_BDOEN                      ((uint32_t)(1UL << 14))
#define SPI_CTL0_CRCEN                      ((uint32_t)(1UL << 13))
#define SPI_CTL0_CRCNT                      ((uint32_t)(1UL << 12))
#define SPI_CTL0_FF16                       ((uint32_t)(1UL << 11))
#define SPI_CTL0_RO                         ((uint32_t)(1UL << 10))
#define SPI_CTL0_SWNSSEN                    ((uint32_t)(1UL << 9))
#define SPI_CTL0_SWNSS                      ((uint32_t)(1UL << 8))
#define SPI_CTL0_LF                         ((uint32_t)(1UL << 7))
#define SPI_CTL0_SPIEN                      ((uint32_t)(1UL << 6))
#define SPI_CTL0_PSC2                       ((uint32_t)(1UL << 5))
#define SPI_CTL0_PSC1                       ((uint32_t)(1UL << 4))
#define SPI_CTL0_PSC0                       ((uint32_t)(1UL << 3))
#define SPI_CTL0_MSTMOD                     ((uint32_t)(1UL << 2))
#define SPI_CTL0_CKPL                       ((uint32_t)(1UL << 1))
#define SPI_CTL0_CKPH                       ((uint32_t)(1UL << 0))
/* CTL1 */
#define SPI_CTL1_TBEIE                      ((uint32_t)(1UL << 7))
#define SPI_CTL1_RBNEIE                     ((uint32_t)(1UL << 6))
#define SPI_CTL1_ERRIE                      ((uint32_t)(1UL << 5))
#define SPI_CTL1_TMOD                       ((uint32_t)(1UL << 4))
#define SPI_CTL1_NSSP                       ((uint32_t)(1UL << 3))
#define SPI_CTL1_NSSDRV                     ((uint32_t)(1UL << 2))
#define SPI_CTL1_DMATEN                     ((uint32_t)(1UL << 1))
#define SPI_CTL1_DMAREN                     ((uint32_t)(1UL << 0))
/* STAT */
#define SPI_STAT_FERR                       ((uint32_t)(1UL << 8))
#define SPI_STAT_TRANS                      ((uint32_t)(1UL << 7))
#define SPI_STAT_RXORERR                    ((uint32_t)(1UL << 6))
#define SPI_STAT_CONFERR                    ((uint32_t)(1UL << 5))
#define SPI_STAT_CRCERR                     ((uint32_t)(1UL << 4))
#define SPI_STAT_TXURERR                    ((uint32_t)(1UL << 3))
#define SPI_STAT_I2SCH                      ((uint32_t)(1UL << 2))
#define SPI_STAT_TBE                        ((uint32_t)(1UL << 1))
#define SPI_STAT_RBNE                       ((uint32_t)(1UL << 0))

/* USBD */
#define USBD                                ((USBD_TypeDef *) USBD_BASE)

#endif /* BITFIELDS_H_ */